apiVersion: aws.example.com/v1alpha1
kind: XNetwork
metadata:
  namespace: default
  name: crossplane-network
spec:
  region: ap-south-1
  cidrBlock: 10.0.0.0/16
  enableDnsSupport: true
  tags:
    - key: project
      value: crossplane-demo
    - key: Environment
      value: demo
    - key: Name
      value: crossplane-network
  subnets:
    - name: public-subnet
      cidrBlock: 10.0.0.0/24
      availabilityZone: ap-south-1a
      mapPublicIPOnLaunch: true
    - name: public-subnet-2
      cidrBlock: 10.0.3.0/24
      availabilityZone: ap-south-1c
      mapPublicIPOnLaunch: true
    - name: private-subnet
      cidrBlock: 10.0.1.0/24
      availabilityZone: ap-south-1a
    - name: private-subnet-2
      cidrBlock: 10.0.2.0/24
      availabilityZone: ap-south-1c
  internetGateway:
    enabled: true
  natGateway:
    enabled: true
  enableSecurityGroups: true
  securityGroups:
    - name: web-lb-sg
      description: Allow HTTP and HTTPS access
      ingress:
        - fromPort: 80
          toPort: 80
          ipProtocol: tcp
          ipRanges:
            - cidrIp: 0.0.0.0/0
        - fromPort: 443
          toPort: 443
          ipProtocol: tcp
          ipRanges:
            - cidrIp: 0.0.0.0/0
    - name: web-sg
      description: Allow HTTP and HTTPS access
      ingress:
        - fromPort: 80
          toPort: 80
          ipProtocol: tcp
          userIdGroupPairs:
            - groupIdRef:
                name: web-lb-sg
        - fromPort: 80
          toPort: 80
          ipProtocol: tcp
          ipRanges:
            - cidrIp: 0.0.0.0/0
    - name: ekscluster-sg
      description: Cluster communication with worker nodes
      ingress:
        - fromPort: 80
          toPort: 80
          ipProtocol: tcp
          ipRanges:
            - cidrIp: 10.0.0.0/8
  providerConfigRef:
    name: crossplane-aws