apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xnetworkings.net.aws.crossplane.awscommunity.io
spec:
  group: net.aws.crossplane.awscommunity.io
  names:
    kind: XNetworking
    plural: xnetworkings
  claimNames:
    kind: Networking
    plural: networkings
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            # defining input parameters
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: ID of this Network that other objects will use to refer to it.
                parameters:
                  type: object
                  description: Network configuration parameters.
                  properties:
                    region:
                      type: string
                  required:
                    - region
              required:
                - id
                - parameters
            # defining return values
            status:
              type: object
              properties:
                subnetIds:
                  type: array
                  items:
                    type: string
                securityGroupClusterIds:
                  type: array
                  items:
                    type: string