apiVersion: apps/v1
kind: Deployment
metadata:
  name: awscommunityday
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: awscommunityday
      branch: main
  template:
    metadata:
      labels:
        app: awscommunityday
        branch: main
    spec:
      imagePullSecrets:
        - name: ecr-secret  # This must match the secret you created
      terminationGracePeriodSeconds: 5
      containers:
        - image: saiyam911/ossjapan:sha-9319ddf #309272221538.dkr.ecr.eu-central-1.amazonaws.com/crossplane-app:latest@sha256:cc370c0a474e2e63fa4f60c90a67399ff911e88abf5e01e16af85073d7f44576
          name: awscommunityday
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
          - name: PORT
            value: "8080"