apiVersion: v1
kind: Service
metadata:
  name: awscommunityday
spec:
  ports:
    - port: 8090
      targetPort: 8000
  # type: NodePort  # Change service type to NodePort
  selector:
    app: awscommunityday
    branch: main