apiVersion: v1
kind: Service
metadata:
  name: awscommunityday
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: NodePort  # Change service type 
  selector:
    app: awscommunityday
    branch: main