apiVersion: v1
kind: Service
metadata:
  name: awscommunityday
spec:
  ports:
    - port: 80
      targetPort: 8098
  type: NodePort  # Change service type to NodePort
  selector:
    app: awscommunityday
    branch: main