apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod 
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: my-nginx-pod 
      image: nginx
      volumeMounts:
        - mountPath: "usr/share/html"
          name: task-pv-storage