apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd//manifests/cluster-install?ref=stable
- argocd-namespace.yaml

patches:
- path: argocd-cm-patch.yaml
- path: argocd-rbac-cm-patch.yaml

namespace: argocd