---
- hosts: all, !localhost
  name: "Setup WordPress docker application"


  remote_user: "{{ system_user }}"
  become: yes
  gather_facts: no
  serial: 1

  vars_prompt:

    - name: domain
      prompt: "\n------
              \n\nSpecify WordPress URL"
      private: no
      default: "{{ wp_domain }}"

    - name: wp_version
      prompt: "\n------
              \n\nSpecify WordPress version you'd like to use"
      private: no
      default: "{{ wp_version }}"

    - name: wp_db_name
      prompt: "\n------
              \n\nSpecify WordPress database name"
      private: no
      default: "{{ wp_db_name }}"

    - name: wp_db_tb_pre
      prompt: "\n------
              \n\nSpecify WordPress table prefix"
      private: no
      default: "{{ wp_db_tb_pre }}"

    - name: wp_db_psw
      prompt: "\n------
              \n\nSpecify WordPress database password"
      private: yes
      default: "{{ wp_db_psw }}"
      confirm: yes

  roles:
  - python
  - docker
  - wordpress-docker
