version: 0.2

env:
  variables:
    AWS_REGION: "eu-central-1"  # Change this to your AWS region
    ECR_REPO_NAME: "crossplane-app"  # Change this to your ECR repository name
    AWS_ACOUNT_NO: "309272221538"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $(aws sts get-caller-identity --query "Account" --output text).dkr.ecr.$AWS_REGION.amazonaws.com
      - REPO_URI=$AWS_ACOUNT_NO.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME
      - echo Cloning the repository...
      - git clone --depth 1 https://github.com/AnikG-Org/devops-practice.git
      - cd devops-practice/crossplane/project/Appbuild/

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $ECR_REPO_NAME .
      - docker tag $ECR_REPO_NAME:$IMAGE_TAG $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Build and push completed successfully.

artifacts:
  files: "**/*"
