---
apiVersion: pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: crossplane-eks-cluster
spec:
  package: 309272221538.dkr.ecr.eu-central-1.amazonaws.com/crossplane-ecr:latest
  packagePullSecrets:
    - name: ecr-secret # Secret for ECR authentication
  packagePullPolicy: Always  # Always pull the latest image 
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  skipDependencyResolution: false
