apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: awscommunityday
  namespace: argocd
  labels:
    crossplane.awscommunity.io: application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/AnikG-Org/devops-practice
    targetRevision: HEAD
    path: crossplane/project/appdeployment
  destination:
    namespace: default
    # name: deploy-target-eks
    server: https://D1BEAC328AF091ED38E5D217EEE1419C.gr7.eu-central-1.eks.amazonaws.com
  syncPolicy:
    automated:
      prune: true    
    retry:
      limit: 5
      backoff:
        duration: 5s 
        factor: 2 
        maxDuration: 1m