apiVersion: v1
kind: Namespace
metadata:
  name: kaniko
---
apiVersion: v1
kind: Secret
metadata:
  name: kanikoazdosecret
  namespace: kaniko
data:
  AZP_TOKEN: __azp-token__
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  namespace: kaniko
  labels:
    name: agent-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agent-deployment
  template:
    metadata:
      labels:
        app: agent-deployment
    spec:
      imagePullSecrets:
      - name: artifactwestregcred
      containers:
      - name: agent-deployment
        image: poclab-docker.artifacts-west.com/azdo-agent/azdo-agent:__commitHash__-__image-tag__
        env:
        - name: AZP_URL
          value: "https://poc.visualstudio.com"
        - name: AZP_POOL
          value: "Platform-Kubernetes-Agents"
        - name: AZP_TOKEN
          valueFrom:
             secretKeyRef:
               name: kanikoazdosecret
               key: AZP_TOKEN