apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: crossplane-app
  namespace: default
spec:
  forProvider:
    instanceType: t2.micro
    region: ap-south-1
    imageId: ami-05c179eced2eb9b5b
    subnetIdRef:
      name: public-subnet
    securityGroupRefs:
      - name: web-sg
    tags:
      - key: Name
        value: crossplane-app
      - key: environment
        value: demo
      - key: project
        value: crossplane
    userData: IyEvYmluL2Jhc2gNCnN1ZG8geXVtIHVwZGF0ZSAteQ0Kc3VkbyB5dW0gaW5zdGFsbCAteSBuZ2lueA0Kc3VkbyBzeXN0ZW1jdGwgc3RhcnQgbmdpbngNCnN1ZG8gc3lzdGVtY3RsIGVuYWJsZSBuZ2lueA0KZWNobyAnSGVsbG8sIEV2ZXJ5b25lIGZyb20gQVdTQ29tbXVuaXR5REFZLDIwMjUhJyB8IHN1ZG8gdGVlIC91c3Ivc2hhcmUvbmdpbngvaHRtbC9pbmRleC5odG1sCg==
  providerConfigRef:
    name: crossplane-aws