version: '3.8'
services:
  web:
    build:  .
    volumes:
      - /root/html:/var/www/html/
    ports:
      - 80:80   
    networks:
      - webnetwork

  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - /root/jenkins_home:/var/jenkins_home
    ports:
      - 8080:80
      - 50000:50000
    networks:
      - webnetwork

networks:
  webnetwork:
    driver: bridge
