apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: crossplane-aws
  namespace: default
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: aws-secret
      key: creds
# ---
# apiVersion: aws.upbound.io/v1beta1
# kind: ProviderConfig
# metadata:
#   name: crossplane-aws-elb
#   namespace: default
# spec:
#   credentials:
#     source: Secret
#     secretRef:
#       namespace: crossplane-system
#       name: aws-secret
#       key: creds