apiVersion: v1
data:
  creds: W2RlZmF1bHRdDQphd3NfYWNjZXNzX2tleV9pZCA9IEFLSUFVUUFRUFM1UklSNlRQUTdODQphd3Nfc2VjcmV0X2
kind: Secret
metadata:
  name: aws-secret
  namespace: crossplane-system
type: Opaque