# In the given playbook the first task is incomplete. Only a name is given. Update the task to use the "apt"
# module to install all required packages. The list of packages to be present are given below. Remember to use loop (with_items) to install all packages in one task:
#         - python
#         - python-setuptools
#         - python-dev
#         - build-essential
#         - python-pip
#         - python-mysqldb
# apt documentation - http://docs.ansible.com/ansible/latest/apt_module.html

# ------------------------------
#           BEFORE
# ------------------------------
#-
#  name: Deploy a web application
#  hosts: db_and_web_server
#  tasks:
#    - name: Install dependencies
# ------------------------------
#           AFTER
# ------------------------------
-
  name: Deploy a web application
  hosts: db_and_web_server
  tasks:
    - name: Install dependencies
      apt: name='{{ item }}' state=present
      with_items:
       - python
       - python-setuptools
       - python-dev
       - build-essential
       - python-pip
       - python-mysqldb
