## We have now added a new monitoring play to monitor the database. However, our playbook spends 6 minutes monitoring web application and once that completes monitors database for 6 minutes. We would like to make this parallel.
## Task: Update poll value for both tasks to 0 to "fire and forget" the monitoring tasks.
## Documentation: http://docs.ansible.com/ansible/latest/playbooks_async.html
#
# ------------------------------
#           BEFORE
# ------------------------------
#-
#  name: Deploy a mysql DB
#  hosts: db_server
#  roles:
#    - python
#    - mysql_db
#
#-
#  name: Deploy a Web Server
#  hosts: web_server
#  roles:
#    - python
#    - flask_web
#
#-
#  name: Monitor Web Application for 6 Minutes
#  hosts: web_server
#  command: /opt/monitor_webapp.py
#  async: 360
#  poll: 30
#
#-
#  name: Monitor Database for 6 Minutes
#  hosts: db_server
#  command: /opt/monitor_database.py
#  async: 360
#  poll: 30

# ------------------------------
#           AFTER
# ------------------------------
-
  name: Deploy a mysql DB
  hosts: db_server
  roles:
    - python
    - mysql_db

-
  name: Deploy a Web Server
  hosts: web_server
  roles:
    - python
    - flask_web

-
  name: Monitor Web Application for 6 Minutes
  hosts: web_server
  command: /opt/monitor_webapp.py
  async: 360
  poll: 0

-
  name: Monitor Database for 6 Minutes
  hosts: db_server
  command: /opt/monitor_database.py
  async: 360
  poll: 0