pipeline {
    agent Devops*
    stages {
        stage('---clean---') {
            steps {
		sh "cd maven/my-app/"
                sh "mvn clean"
            }
        }
        stage('--test--') {
            steps {
                sh "mvn test"
            }
        }
        stage('--package--') {
            steps {
                sh "mvn package"
            }
        }
    }
}
