# Variable file for host db_and_web_server

# ------------------------------
#           BEFORE
# ------------------------------

# ------------------------------
#           AFTER
# ------------------------------

ansible_ssh_pass: Passw0rd
ansible_host: 192.168.1.14
