apiVersion: v1

kind: Pod

metadata:
  name: my-app
  namespace: prod
  labels: 
    app: myapp
    location: india
    type: front-end


spec:
  restartPolicy: Never
  #volumes:
  #- name: shared-data
  #  emptyDir: {}
  
  containers:
    - name: nginx-container
      image: nginx:alpine
      #volumeMounts:
      #  - name: shared-data
      #    mountPath: /usr/share/nginx/html
      resources:
        limits:
          cpu: "1"
          memory: 500Mi
        requests:
          cpu: "0.5"
          memory: 256Mi
      ports:
        - containerPort: 80

    - name: database
      image: reddis
      ports:
        - containerPort: 6379
      resources:
        limits:
          cpu: "1"
          memory: 500Mi
        requests:
          cpu: "0.5"
          memory: 256Mi
