apiVersion: v1
kind: Pod

metadata:
  name: my-app
  lebels: 
    app: myapp
    type: front-end


spec:
  
  containers:
    - name: nginx-container
      image: nginx:alpine
      resources:
        limits:
          cpu: "1"
          memory: 500Mi
        requests:
          cpu: "0.5"
          memory: 256Mi
      ports:
        - containerPort: 80

  tolerations:                  #taint-effect ><type>> NoSchedule | PreferNoSchedule | NoExecte
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedule"