#>kubectl label nodes node01 color=blue     #node label color=blue

apiVersion: apps/v1
kind: Deployment

metadata:
  name: blue

spec:
  replicas: 6
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels: 
        run: nginx

    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: "1"
            memory: 500Mi
          requests:
            cpu: "0.5"
            memory: 256Mi
      tolerations:
      - key: "color"
        operator: "Equal"
        value: "blue"
        effect: "NoSchedule"

      affinity:                 
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: color
                operator: In
                values:
                - "blue"   