apiVersion: v1
kind: Pod

metadata:
  name: simple-webapp-color
  annotations:                       #Kubernetes annotations to attach arbitrary non-identifying metadata to objects
    imageregistry: "https://hub.docker.com/"
    application-version: "v1.0"
  labels: 
    app: simple-webapp-color
    type: front-end


spec:
  restartPolicy: OnFailure
  containers:
    - name: simple-webapp-color
      image: mmumshad/simple-webapp-color
      command: ["sleep"]            #override dockerfile ENTRYPOINT instruction
      args: ["0"]                   #override dockerfile CMD instruction
      resources:
        limits:
          cpu: "1"
          memory: 500Mi
        requests:
          cpu: "0.5"
          memory: 256Mi
      ports:
        - containerPort: 8080
      
      env:                          #env variable on pod based on application
        - name: APP_COLOR
          value: black