# Declarative approiach
apiVersion: v1
kind: Secret
metadata:
  name: appsecret
type: Opaque
data:
  USER: <hashed_User>           #for hashed value>> echo –n ‘<value>’ | base64 >>use >> O/P>> <hashed_value> and decode later >> echo ‘<hashvalue>’ | base64 --decode 
  password: <hashed_Password>   
