apiVersion: v1
kind: Pod

metadata:
  name: simple-webapp-color
  labels: 
    app: simple-webapp-color
    type: front-end

spec:
  containers:
    - name: simple-webapp-color
      image: mmumshad/simple-webapp-color
      resources:
        limits:
          cpu: "1"
          memory: 500Mi
        requests:
          cpu: "0.5"
          memory: 256Mi
      ports:
        - containerPort: 8080
      
      envFrom:
        - secretRef:              #map secret file metadata
            name: appsecret   