apiVersion: v1
kind: Pod

metadata:
  name: webapp-with-log-agent
  labels: 
    app: webapp-color
    multipod-app: 'simple-webapp-color + prometheus agent'
    type: front-end

spec:
  containers:
    - name: simple-webapp-color
      image: mmumshad/simple-webapp-color
      resources:
        limits:
          cpu: "1"
          memory: 500Mi
        requests:
          cpu: "0.5"
          memory: 256Mi
      ports:
        - containerPort: 8080

    - name: log-agent
      image: prom/node-exporter
      resources:
        limits:
          cpu: "0.5"
          memory: 100Mi
        requests:
          cpu: "0.2"
          memory: 10Mi
      ports:
        - containerPort: 9100