apiVersion: v1
kind: ServiceAccount
metadata:
  name: SA2
  #namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: SA2-ClusterRole
  labels:
    rbac.example.com/aggregate-to-monitoring: "true"
    name: SA2-ClusterRole
rules:
- apiGroups: [""]
  resources: ["endpoints", "nodes", "secrets"]
  verbs: ["admin","edit","list","view", "watch"]

- apiGroups: ["*"]      #wide access
  resources: ["*"]
  verbs: ["*"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: SA2-ClusterRoleBinding
  labels:
    name: SA2-ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: SA2-ClusterRole
subjects:
- kind: ServiceAccount
  name: SA2
- kind: User
  name: michelle
---
