apiVersion: v1
kind: Config
current-context: admin-prod@production
preferences: {}
clusters: 

- name: production
  cluster:
    certificate-authority: path/to/cluster-kubernetes/pki/ca.crt
    server: https://172.17.0.51:6443
- name: dev
  cluster:
    certificate-authority-data: ${CLUSTER_CA_ENCODED}
    server: https://172.18.0.51:6443
- name: local
  cluster:
    insecure-skip-tls-verify: true
    server: https://5.6.7.8:6443

users:

- name: admin-prod
  user:
    client-certificate: path/to/my/user/admin.crt
    client-key: path/to/my/user/admin.key
- name: admin-dev
  user:
    client-certificate-data: ${CLIENT_CERTIFICATE_DATA_ENCODED}
    client-key-data: ${CLIENT_CERTIFICATE_KEY_DATA_ENCODED}
- name: admin-local
  user:
    password: some-password
    username: exp

contexts:

- name: admin-prod@production
  context:
      cluster: production
      user: admin-prod
      namespace: prod
- name: admin-dev@production
  context:
      cluster: dev
      user: admin-dev
      namespace: dev
- name: admin-local@local
  context:
      cluster: local
      user: admin-local
      namespace: default