---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx-app
    image: your-registry-server/apps/internal-app
    resources:
        limits:
          cpu: "1"
          memory: 500Mi
        requests:
          cpu: "0.5"
          memory: 256Mi

  imagePullSecrets:
  - name: regcred

---
#> docker-registry secret create #kubectl CMD

kubectl create secret docker-registry regcred --docker-server=your-registry-server --docker-username=your-name --docker-password=your-pword --docker-email=your-email --dry-run=client -o yaml > docker-reg-cred.yaml

#> cat docker-reg-cred.yaml
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJ5b3VyLXJlZ2lzdHJ5LXNlcnZlciI6eyJ1c2VybmFtZSI6InlvdXItbmFtZSIsInBhc3N3b3JkIjoieW91ci
kind: Secret
metadata:
  creationTimestamp: null
  name: regcred
type: kubernetes.io/dockerconfigjson
---
kubectl get secret regcred -o yaml		
kubectl get secret regcred --output="jsonpath={.data.\.dockerconfigjson}" | base64 --decode		#to decode reg cred