apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - image: alpine
    name: alpine
    resources:
        limits:
          cpu: "1"
          memory: 500Mi
        requests:
          cpu: "0.5"
          memory: 256Mi
    command: ["/bin/sh","-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]

    volumeMounts:
    - mountPath: /opt
      name: localhost-data-volume
    - mountPath: /opt
      name: aws-data-volume

  volumes:                          
  - name: localhost-data-volume
    hostPath:                          #localhost:docker mounting /data:/opt
      path: /data
      type: Directory

  - name: aws-data-volume              #aws-ebs:docker mounting
    awsElasticBlockStore:
      volumeID: <volume-id>
      fsType: ext4