# Dynamic pv provitioning
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: aws-ebs
  labels:
    name: aws-ebs
    cloud: aws
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  #iopsPerGB: "10"
  fsType: ext4 
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate    # WaitForFirstConsumer mode which will delay the binding and provisioning of a PersistentVolume until a Pod using the PersistentVolumeClaim is created
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk
  labels:
    name: azure-disk
    cloud: azure
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
  kind: Managed
  #location: eastus
  storageAccount: azure_storage_account_name
volumeBindingMode: WaitForFirstConsumer      #By default, the Immediate mode indicates that volume binding and dynamic provisioning occurs once the PersistentVolumeClaim is created
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gce-pd
  labels:
    name: gce-pd
    cloud: gcp
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fstype: ext4
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage                     #local storage
  managedFields:
  - apiVersion: storage.k8s.io/v1
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer