apiVersion: v1
kind: ResourceQuota

metadata:
  name: compute-quota
  namespace: prod

spec:
    hard:
      pods: "20"
      requests.cpu: "50"
      requests.memory: 800Mi
      limits.cpu: "100"
      limits.memory: 2Gi
