apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-service
spec:
  type: NodePort
  ports:
  - targetPort: 80                  #frontend pod app port
    port: 80                        #service port
    nodePort: 30008                 #range of nodePort: 30000-32767 - main node port

  selector:                         #selector used to match lebel of pods
    app: myapp      
    type: front-end                 