apiVersion: v1
kind: Service
metadata:
  name: myapp-nodeport-service
spec:
  type: LoadBalancer                #this mostly used in spported cloud platform
  ports:
  - targetPort: 80                  #frontend pod app port
    port: 80                        #service port
    nodePort: 30008                 #range of nodePort: 30000-32767 - main node port
    protocol: TCP

  selector:
    app: myapp      
    type: front-end                 #taking pod-defination label for targetPort