apiVersion: v1
kind: Service
metadata:
  name: jenkins-svc
  namespace: devops
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: jenkins-controler
  type: NodePort  
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080