apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ include "jenkins-chart.namespace" . }}
  labels:
    {{- include "jenkins-chart.labels" . | nindent 4 }}
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8080'
spec:
  selector: 
    app: {{ .Values.deployment.app }}
  type: {{ .Values.service.serviceType }} 
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      {{- if (and (eq .Values.service.serviceType "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}


